# Generated by Django 4.2.3 on 2023-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telegramrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramrequests',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
