# Generated by Django 4.2.3 on 2023-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telegramrequests_in_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramrequests',
            name='request_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
