# Generated by Django 4.2.3 on 2023-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_telegramrequests_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramrequests',
            name='request_id_ext',
            field=models.BigIntegerField(default=0),
        ),
    ]
