version: "3.8"

services:  
  api.telegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.telegram
    restart: always
    entrypoint:
      - "/api/docker-entrypoint.sh"
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    ports:
      - "8002:8000"
    volumes:
      - .:/code
    env_file:
      - .env

  bot.telegram:
    build:
      context: .
      dockerfile: DockerfileBot
    container_name: bot.telegram
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - api.telegram
      
  producer.telegram:
    build:
      context: .
      dockerfile: DockerfileProducer
    container_name: producer.telegram
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - api.telegram

  consumer.telegram:
    build:
      context: .
      dockerfile: DockerfileConsumer
    container_name: consumer.telegram
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - api.telegram

volumes:
  postgres_data:

networks:
    docker_nw:
        driver: bridge
        external: true
