version: "3.8"

services:  
  api.gpt-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.gpt-service
    restart: always
    entrypoint:
      - "/api/docker-entrypoint.sh"
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    env_file:
      - .env
      
  producer.gpt-service:
    build:
      context: .
      dockerfile: DockerfileProducer
    container_name: producer.gpt-service
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - api.gpt-service
  consumer.gpt-service:
    build:
      context: .
      dockerfile: DockerfileConsumer
    container_name: consumer.gpt-service
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - api.gpt-service

volumes:
  postgres_data:

networks:
    docker_nw:
        driver: bridge
        external: true
