version: "3.8"

services:
  autocontent_pg:
    image: postgres:14
    container_name: autocontent_pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - docker_nw
    env_file:
      - ./.env
    ports:
      - "5433:5432"

volumes:
  postgres_data:

networks:
    docker_nw:
        driver: bridge
        external: true
