#!/bin/bash
set -e

psql <<- EOSQL
	CREATE DATABASE requests;
	CREATE USER $REQUESTS_USER WITH PASSWORD '$REQUESTS_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE requests TO $REQUESTS_USER;
    
	CREATE DATABASE gpt_service;
	CREATE USER $GPT_USER WITH PASSWORD '$GPT_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE requests TO $GPT_USER;
	GRANT ALL PRIVILEGES ON DATABASE $GPT_USER TO $GPT_USER;
	
	CREATE DATABASE telegram_service;
	CREATE USER $TELEGRAM_USER WITH PASSWORD '$TELEGRAM_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE requests TO $TELEGRAM_USER;
	GRANT ALL PRIVILEGES ON DATABASE $TELEGRAM_USER TO $TELEGRAM_USER;
	
	CREATE DATABASE tts_service;
	CREATE USER $TTS_USER WITH PASSWORD '$TTS_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE requests TO $TELEGRAM_USER;
	GRANT ALL PRIVILEGES ON DATABASE $TELEGRAM_USER TO $TELEGRAM_USER;
	
	CREATE DATABASE ggl_service;
	CREATE USER $GOOGLE_USER WITH PASSWORD '$GOOGLE_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE requests TO $GOOGLE_USER;
	GRANT ALL PRIVILEGES ON DATABASE $GOOGLE_USER TO $GOOGLE_USER;
EOSQL