# Generated by Django 4.2.3 on 2023-07-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('language_code', models.CharField(blank=True, help_text="Telegram client's lang", max_length=8, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gpt_users',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestsModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_src', models.CharField(max_length=255)),
                ('request_text', models.TextField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'gpt_requests',
            },
        ),
        migrations.CreateModel(
            name='RequestStatusesModel',
            fields=[
                ('request_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.requestsmodel')),
                ('audio_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_status', to='api.statusesmodel')),
                ('gpt_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gpt_status', to='api.statusesmodel')),
                ('video_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_status', to='api.statusesmodel')),
            ],
            options={
                'db_table': 'requests_status',
            },
        ),
    ]
