# Generated by Django 4.2.3 on 2023-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestsmodel',
            table='requests',
        ),
        migrations.AlterModelTable(
            name='user',
            table='requests_users',
        ),
    ]
