# Generated by Django 4.0.10 on 2023-07-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='gpt_users',
        ),
    ]
