# Generated by Django 4.0.10 on 2023-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
