# Generated by Django 4.0.10 on 2023-07-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_gpt_tokens_alter_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dialogsmodel',
            table='gpt_dialogs',
        ),
    ]
