# Generated by Django 4.0.10 on 2023-07-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dialogsmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dialogsmodel',
            table=None,
        ),
    ]
