# Generated by Django 4.0.10 on 2023-07-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dialogsmodel_table_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DialogsModel',
        ),
    ]
