# Generated by Django 4.0.10 on 2023-07-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_dialogsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='RequestsModel',
        ),
    ]
