# Generated by Django 4.0.10 on 2023-07-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_statusesmodel_requeststatusesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestStatusesModel',
        ),
        migrations.DeleteModel(
            name='StatusesModel',
        ),
    ]
