# Generated by Django 4.0.10 on 2023-07-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_statusesmodel_requeststatusesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeststatusesmodel',
            name='audio_status',
        ),
        migrations.RemoveField(
            model_name='requeststatusesmodel',
            name='gpt_status',
        ),
        migrations.RemoveField(
            model_name='requeststatusesmodel',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='requeststatusesmodel',
            name='video_status',
        ),
        migrations.DeleteModel(
            name='RequestsModel',
        ),
        migrations.DeleteModel(
            name='RequestStatusesModel',
        ),
        migrations.DeleteModel(
            name='StatusesModel',
        ),
    ]
