version: "3.8"

services:  
  api.ggl-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.ggl-service
    restart: always
    entrypoint:
      - "/api/docker-entrypoint.sh"
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    ports:
      - "8004:8000"
    volumes:
      - .:/code
    env_file:
      - .env
      
  producer.ggl-service:
    build:
      context: .
      dockerfile: DockerfileProducer
    container_name: producer.ggl-service
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env
  consumer.ggl-service:
    build:
      context: .
      dockerfile: DockerfileConsumer
    container_name: consumer.ggl-service
    restart: always
    environment:
      - DJANGO_PROD=true
    networks:
      - docker_nw
    volumes:
      - .:/code
    env_file:
      - .env

volumes:
  postgres_data:

networks:
    docker_nw:
        driver: bridge
        external: true
